[package]
name = "cache-rpc"
version = "0.1.0"
authors = ["Alexander Polakov <a.polakov@iconic.vc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3"
actix = "0.10"
actix-codec = "0.3"
tokio = { version = "0.2", features = ["sync", "time", "macros"] }
bytes = "0.5"
serde = "1.0"
serde_json = { version = "1.0", features = ["raw_value"] }
awc = { version = "2", features = ["openssl"] }
bs58 = "0.4"
dashmap = "4"
futures-util = "0.3"
stream_generator = "0.1"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
structopt = "0.3"
base64 = "0.13"
zstd = "0.8"
smallvec = { version = "1.6", features = ["serde", "union"] }
thiserror = "1.0"
prometheus = { version = "0.12", default-features = false, features = ["process"] }
once_cell = "1.7"
lru = "0.6"
