[package]
name = "cache-rpc"
version = "0.1.0"
authors = ["Alexander Polakov <a.polakov@iconic.vc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3"
actix = "0.10"
actix-codec = "0.3"
tokio = { version = "0.2", features = ["sync", "time"] }
bytes = "0.5"
serde = "1.0"
serde_json = "1.0"
awc = { version = "2", features = ["openssl"] }
bs58 = "0.4"
dashmap = "4"
futures-util = "0.3"
